version: '3.4'
services:
  nginx:
    image: nginx:1.15.9
    networks:
      - reverse_proxy
    volumes:
      - logs:/var/log/nginx
      - cache:/etc/nginx/cache
    env_file:
      - ../env/.env
      - ../env/.nginx
    configs:
      - source: nginx_default_conf
        target: /etc/nginx/conf.d/default.conf
      - source: nginx_key_api_key
        target: /etc/nginx/api.chalice.top.key
      - source: nginx_key_api_pem
        target: /etc/nginx/api.chalice.top.pem
      - source: nginx_key_pem
        target: /etc/nginx/chalice.top.pem
      - source: nginx_key_key
        target: /etc/nginx/chalice.top.key
      - source: nginx_key_www_key
        target: /etc/nginx/www.chalice.top.key
      - source: nginx_key_www_pem
        target: /etc/nginx/www.chalice.top.pem

    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    ports:
      - target: 8000
        published: 8000
        mode: host
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host

networks:
  reverse_proxy:

configs:
  nginx_default_conf:
    file: ../configs/nginx/default.conf
  nginx_key_api_key:
    file: /nginx_key/api.chalice.top.key
  nginx_key_api_pem:
    file: /nginx_key/api.chalice.top.pem
  nginx_key_pem:
    file: /nginx_key/chalice.top.pem
  nginx_key_key:
    file: /nginx_key/chalice.top.key
  nginx_key_www_pem:
    file: /nginx_key/www.chalice.top.pem
  nginx_key_www_key:
    file: /nginx_key/www.chalice.top.key

volumes:
  logs:
  cache:
